#!/bin/sh

PREREQS="udev"

prereqs() { echo "$PREREQS"; }

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

if [ ! -x /sbin/multipath ]; then
	exit 0
fi

. /usr/share/initramfs-tools/hook-functions

add_bindings()
{
  if [ -r /etc/multipath/bindings ]; then 
      mkdir -p $DESTDIR/etc/multipath
      cp /etc/multipath/bindings $DESTDIR/etc/multipath/
  fi
}

copy_exec /sbin/multipath /sbin
copy_exec /sbin/kpartx /sbin
copy_exec /sbin/dmsetup /sbin
copy_exec /lib/multipath/libcheckcciss_tur.so /lib/multipath
copy_exec /lib/multipath/libcheckdirectio.so /lib/multipath
copy_exec /lib/multipath/libcheckemc_clariion.so /lib/multipath
copy_exec /lib/multipath/libcheckhp_sw.so /lib/multipath
copy_exec /lib/multipath/libcheckrdac.so /lib/multipath
copy_exec /lib/multipath/libcheckreadsector0.so /lib/multipath
copy_exec /lib/multipath/libchecktur.so /lib/multipath
copy_exec /lib/multipath/libmultipath.so /lib/multipath
copy_exec /lib/multipath/libprioalua.so /lib/multipath
copy_exec /lib/multipath/libprioconst.so /lib/multipath
copy_exec /lib/multipath/libprioemc.so /lib/multipath
copy_exec /lib/multipath/libpriohds.so /lib/multipath
copy_exec /lib/multipath/libpriohp_sw.so /lib/multipath
copy_exec /lib/multipath/libprionetapp.so /lib/multipath
copy_exec /lib/multipath/libpriorandom.so /lib/multipath
copy_exec /lib/multipath/libpriordac.so /lib/multipath

[ -r /etc/multipath.conf ] && cp /etc/multipath.conf $DESTDIR/etc/
add_bindings

for x in dm-multipath dm-round-robin scsi_dh scsi_dh_rdac scsi_dh_hp_sw scsi_dh_emc scsi_dh_alua; do
	manual_add_modules ${x}
done

